### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#119]
Issue created by migration from Trac.

Original creator: aberl2

Original creation time: 2013-07-17 06:18:57

Assignee: @tkralphs

Version: 5.4.8

There is a build error under Windows using autotools and mingw/cl compiler. Cgl library does not compile. The same holds for lates Cgl project.

 g++ -DHAVE_CONFIG_H -I. -I. -I/c/home/software/library/SYMPHONY-5.4.8/CoinUtils
/src -I/c/home/software/library/SYMPHONY-5.4.8/Osi/src/Osi -I/c/home/software/li
brary/SYMPHONY-5.4.8/CoinUtils/src -O3 -pipe -DNDEBUG -pedantic-errors -Wparenth
eses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversio
n -Wno-unknown-pragmas -Wno-long-long -DCGL_BUILD -MT CglTreeInfo.lo -MD -MP -MF
 .deps/CglTreeInfo.Tpo -c CglTreeInfo.cpp -o CglTreeInfo.o
/bin/sh ../../libtool --tag=CXX --mode=link g++  -O3 -pipe -DNDEBUG -pedantic-er
rors -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strin
gs -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCGL_BUILD   -o libCgl.la
 -rpath /c/home/software/library/SYMPHONY-5.4.8/lib -version-info 8:4:7 CglCutGe
nerator.lo CglMessage.lo CglStored.lo CglParam.lo CglTreeInfo.lo CglAllDifferent
/libCglAllDifferent.la CglClique/libCglClique.la CglDuplicateRow/libCglDuplicate
Row.la CglFlowCover/libCglFlowCover.la CglGomory/libCglGomory.la CglKnapsackCove
r/libCglKnapsackCover.la CglLandP/libCglLandP.la CglLiftAndProject/libCglLiftAnd
Project.la CglMixedIntegerRounding/libCglMixedIntegerRounding.la CglMixedInteger
Rounding2/libCglMixedIntegerRounding2.la CglOddHole/libCglOddHole.la CglPreProce
ss/libCglPreProcess.la CglProbing/libCglProbing.la CglRedSplit/libCglRedSplit.la
 CglResidualCapacity/libCglResidualCapacity.la CglSimpleRounding/libCglSimpleRou
nding.la CglTwomir/libCglTwomir.la
libtool: link: warning: undefined symbols not allowed in i686-pc-mingw32 shared
libraries
rm -fr  .libs/libCgl.lax
rm -fr .libs/libCgl.lax
mkdir .libs/libCgl.lax
rm -fr .libs/libCgl.lax/libCglAllDifferent.a
mkdir .libs/libCgl.lax/libCglAllDifferent.a
(cd .libs/libCgl.lax/libCglAllDifferent.a && ar x /c/home/software/library/SYMPH
ONY-5.4.8/Cgl/src/CglAllDifferent/.libs/libCglAllDifferent.a)
libtool: link: ERROR: object name conflicts: .libs/libCgl.lax/libCglAllDifferent
.a//c/home/software/library/SYMPHONY-5.4.8/Cgl/src/CglAllDifferent/.libs/libCglA
llDifferent.a
make[4]: *** [libCgl.la] Error 1
make[4]: Leaving directory `/c/home/software/library/SYMPHONY-5.4.8/Cgl/src'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/c/home/software/library/SYMPHONY-5.4.8/Cgl/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/c/home/software/library/SYMPHONY-5.4.8/Cgl/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/c/home/software/library/SYMPHONY-5.4.8/Cgl'
make: *** [all-recursive] Error 1

**Comment by tkralphs** [comment]
This should be resolved in latest versions.
