### ISSUE TITLE
Not able to brew symphony (El Capitan with right chown)

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#146]
Issue created by migration from Trac.

Original creator: tomthebuzz

Original creation time: 2015-10-23 16:03:26

Assignee: menal

Version: stable/5.2 (SVN)

CC:  tomthebuzz@me.com

Keywords: brew, symphony, el capitan

Dear CoinOr Team,

am not able to brew / tap symphony under the latest El Capitan OS X release. Brew update & doctor show all things correct and in place. Are you still in the process of updating the formulae or should this work and is only an issue from my end.

Have installed brew into /usr/local and updated rights as per tips & tricks.

Cheers
-Tom

**Comment by svigerske** [comment]
Comment by tomthebuzz created at 2015-10-23 16:04:02

Oh, and BTW your ticketing system has an SMTP config error...

**Comment by tkralphs** [comment]
The formula should work now. If not, please reopen the issue.
