### ISSUE TITLE
Not able to manually install rSymphony on El Capitan

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#147]
Issue created by migration from Trac.

Original creator: tomthebuzz

Original creation time: 2015-10-26 14:46:33

Assignee: menal

Version: stable/5.2 (SVN)

Keywords: OS X, Rsymphony, R, El Capitan

Have already reported that the brew based install doesn't work anymore under OS X El Capitan.
While I was able to manually make, install and test Symphony on the new OS X El Capitan I wasn't able to subsequently  install the corresponding R-Package rSymphony.

Do you know whether there are any special parameters required during the make / install to ensure compatibility with the r-package?

Thanks & Best Regards
-Tom

**Comment by tkralphs** [comment]
I guess a lot has changed since this was reported. There were some issues with the original SYMPHONY R package and there seem to be some new ones out there that probably work better, such as `lpsymphony` and `Rsymphony_solve`.
