### ISSUE TITLE
Installation of Symphony on Windows 8.1 by mingw

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#149]
Issue created by migration from Trac.

Original creator: harpreetmertia

Original creation time: 2016-02-17 07:12:16

Assignee: menal

Version: 

I am trying to link symphony to Scilab. I have done it for Linux. Now I am trying to build it in Windows I have tried it with MS Visual Studio 2010 but it generates static libraries (*.lib) files. I want dll files. I tried to build it using mingw but following error was coming in Clp. PFA

**Comment by svigerske** [comment]
Attachment [error.png](https://www.coin-or.org/issue-attachments/SYMPHONY/ticket149/error.png) by harpreetmertia created at 2016-02-17 07:14:21

Error shown in the end

**Comment by tkralphs** [comment]
This is not currently supported, but will be in an upcoming version of the build tools.
