### ISSUE TITLE
Symphony of my iMac

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#151]
Issue created by migration from Trac.

Original creator: kahodo1

Original creation time: 2016-04-29 12:40:31

Assignee: @tkralphs

Version: 

Hi 

I am trying to install Symphony on my iMac to enable me run my model with the R version (Rsymphony). The system tells me I require Symphony but I can't download it.

Is there a way to do it?

Regards

Kwadjo

**Comment by tkralphs** [comment]
The easiest way to do this is to install SYMPHONY via [Homebrew](https://brew.sh):
```
brew install gcc wget svn git
brew tap coin-or-tools/coinor
brew install symphony
```
See [here](https://github.com/coin-or/SYMPHONY/blob/master/INSTALL.md#building-on-os-x) for details. There were some problems reported with building the SYMPHONY R interface a while back so feel free to report here if you have any further issues.

**Comment by tkralphs** [comment]
You might also check out some alternatives that have appeared and may have resolved the existing issues, such as `lpsymphony` and `Rsymphony_solve`.
