### ISSUE TITLE
trouble with using cplex as lp solver with SYMPHONY 5.6

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#152]
Issue created by migration from Trac.

Original creator: agamemnon314

Original creation time: 2017-04-12 02:21:37

Assignee: menal

Version: 5.6.16

Keywords: cplex

./configure --with-cplex-incdir="/opt/ibm/ILOG/CPLEX_Studio1271/cplex/include/ilcplex" --with-cplex-lib="-L/opt/ibm/ILOG/CPLEX_Studio1271/cplex/lib/x86-64_linux/static_pic -lcplex -lpthread -lm"

checking if user provides library for Cplex... yes
checking whether symbol CPXgetstat is available with CPX... no
configure: error: Cannot find symbol(s) CPXgetstat with CPX
configure: error: /bin/bash './configure' failed for Osi

**Comment by svigerske** [comment]
Attachment [config.log](https://www.coin-or.org/issue-attachments/SYMPHONY/ticket152/config.log) by agamemnon314 created at 2017-04-12 02:22:06

**Comment by tkralphs** [comment]
To debug, I would need the `config.log` of `Osi` itself. If this is still a problem, please reopen this ticket and post that file.
