### ISSUE TITLE
Problems with cuts

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#153]
Issue created by migration from Trac.

Original creator: gpantuza

Original creation time: 2017-06-13 20:59:49

Assignee: @tkralphs

Version: 

Dear, I'm new on SYMPHONY. I'm trying to implement the TSP with the subtour elimination constraint relaxed.  How can I insert this constraint as a cut?  I've tried using cg_add_explicit_cut and cg_add_user_cut functions, but in both cases, I always have the relaxad result. Or, Is there any function to insert this restriction in a lazy fashion?

Thank you.

**Comment by tkralphs** [comment]
Check the [VRP application](https://github.com/coin-or/SYMPHONY/tree/master/SYMPHONY/Applications/VRP) for an example of how to do this. It is adding a generalized version of the subtour elimination constraints.
