### ISSUE TITLE
libSymAppl.la being built but not installed

### ISSUE THREAD

**Issue by babailey471340** [coin-or/SYMPHONY#187]
Tried installing via:
`./coinbrew build symphony@5.6.18 --with-application`
but `libSymAppl.la` was not put in the `dist` directory.

Searched `build/symphony/5.6.18/SYMPHONY/src/` and found it there.

This could be a regression from https://github.com/coin-or/SYMPHONY/issues/159, since, as in that issue, running `make install` again from `build/symphony/5.6.18` performs the copy and linking into `dist/include`.

**Comment by tkralphs** [comment]
Hmm, you're right, my previous fix was rubbish. Honestly, I don't know what I was thinking or why it seemed to work before. I just committed a new fix, which does seem to do the trick. Can you give it a try? Just build `5.6` instead of `5.6.18` with coinbrew.

**Comment by babailey471340** [comment]
Doesn't look like the behavior was altered.

Put a copy of coinbrew in a fresh directory, ran `./coinbrew build symphony@5.6 --with-application` and then:
`$ ls dist/lib/libSymAppl.*`
`ls: cannot access dist/lib/libSymAppl.*: No such file or directory`
`$ ls build/symphony/5.6/SYMPHONY/src/libSymAppl.*`
`build/symphony/5.6/SYMPHONY/src/libSymAppl.la`

**Comment by tkralphs** [comment]
Argh, sorry for the run-around. I think I finally see what the correct fix should be for this and have committed it in 112c341b. If you would be so kind, can you give this one more try?

**Comment by babailey471340** [comment]
That got most of the way there.  Ran `./coinbrew build symphony@5.6 --with-application` in a fresh directory and then:
`$ ls dist/lib/libSymAppl.*`
`dist/lib/libSymAppl.la  dist/lib/libSymAppl.so.0`
`dist/lib/libSymAppl.so  dist/lib/libSymAppl.so.0.0.0`

Checked the other `*.so*` files/symlinks and they're all named without version numbers.  Not sure if that's an artifact of the fix or a difference between building 5.6 vs. 5.6.18; I no longer have the previous build test I did with 5.6 around to make sure.

**Comment by tkralphs** [comment]
Yes, only releases have libtool version numbers, since the libtool versioning scheme doesn't really allow for a way to get version numbers for non-releases. Now that everything is working, I'll make a `5.6.19` release and that will produce libraries with version numbers. Thanks for your help in resolving this!
