### ISSUE TITLE
License file/readme mismatch

### ISSUE THREAD

**Issue by ankane** [coin-or/SYMPHONY#188]
Hi, just wanted to let you know the readme says Eclipse Public License 2.0, but the license file is for 1.0.

**Comment by tkralphs** [comment]
Thanks for pointing this out! It is fixed in [3e2bd1a](https://github.com/coin-or/SYMPHONY/commit/3e2bd1a1b359c17700c3b7391ce5a7fa285e929c).

**Comment by ankane** [comment]
Great, thanks @tkralphs!
