### ISSUE TITLE
SYMPHONY 5.6.19 build fails in MSys2 due to pwd.h missing.

### ISSUE THREAD

**Issue by ahmtsn** [coin-or/SYMPHONY#189]
Hello. I have successfully built Cbc. Similarly I have tried building SYMPHONY from source with the following command line:

`
 ./coinbrew build SYMPHONY --enable-optional --with-application --enable-openmp --with-gmpl --enable-sensitivity-analysis --enable-gnu-packages --build=x86_64-w64-mingw32
`

I get the following error at the end.

> ... Installing ThirdParty/Glpk 1.10.7
> ...Installing Data/Sample 1.2.12
> ...Installing CoinUtils 2.11.6
> ...Installing Osi 0.108.7
> ...Installing Clp 1.17.7
> ...Installing Cgl 0.60.6
> ...Reconfiguring SYMPHONY 5.6.19
> ...Building SYMPHONY 5.6.19
> ...
> D:/msys64/home/ChiccoRab/coinbrew/SYMPHONY/SYMPHONY/src/Master/main.c:58:10: fatal error: pwd.h: No such file or directory
>    58 | #include <pwd.h>
>       |          ^~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:9371: symphony-main.o] Error 1
> make: *** [Makefile:660: all-recursive] Error 1
> Error: Build failed, see error output above

Could you please help me building SYMPHONY?

I have used installing instructions from [https://coin-or.github.io/user_introduction.html#building-with-gcc-in-msys2](https://coin-or.github.io/user_introduction.html#building-with-gcc-in-msys2). 

Some info about the bash shell I use:

`$ which gcc --->
/mingw64/bin/gcc`. 

`$ find -name pwd.h --->
./usr/include/pwd.h
`

Note: Since there are some minor differences in the [https://coin-or.github.io/SYMPHONY/doc/SYMPHONY-5.6.19-Manual.pdf](https://coin-or.github.io/SYMPHONY/doc/SYMPHONY-5.6.19-Manual.pdf), I also went through with the process defined in the manual which ended up with the same error I presented above.

Sincerely

**Comment by tkralphs** [comment]
Thanks for the detailed report. I was able to replicate this. The problem seems to be related to `readline`, which gets linked in because of `--enable-gnu-packages`. I guess that without that addition to the command line, everything will be fine. Anyway, I hope this should be an easy fix.

**Comment by tkralphs** [comment]
Should be fixed in `stable/5.6` by 4227231 and a2ae571. It works in my testing, but can you please give it a try? Feel free to re-open if it's still broken for you.

**Comment by ahmtsn** [comment]
Hello. Thank you for quick reply. I ran the command line again, this time without `--enable-gnu-packages`, and SYMPHONY installed successfully. I am able to load and solve mps files. 
Sincerely.

**Comment by tkralphs** [comment]
Would you mind trying with `--enable-gnu-packages` just so I know that the problem you originally reported is fixed?

**Comment by ahmtsn** [comment]
Hello. I ran the following command:
`./coinbrew fetch build SYMPHONY@stable/5.6 --enable-optional --with-application --enable-openmp --with-gmpl --enable-sensitivity-analysis --enable-gnu-packages --build=x86_64-w64-mingw32`

SYMPHONY 5.6 installed ok. I tested on some of the sample problems both "command line interface" and "interactive shell" seem to be working. 

Does having `--build=x86_64-w64-mingw32` mean solution process (and math) is bounded by 32-bit capacity? Would it be possible (or necessary) to change the build to an equivalent of, say, `--build=x86_64-w64-mingw**64**`? 

Sincerely.

**Comment by tkralphs** [comment]
> Does having --build=x86_64-w64-mingw32 mean solution process (and math) is bounded by 32-bit capacity? Would it be possible (or necessary) to change the build to an equivalent of, say, --build=x86_64-w64-mingw**64**

No, that strong refers to the build environment, not the target architecture. You are almost surely using a 64-bit version of MSys and that is string corresponding to it. I don't know exactly why that 32 is there, the important thing (I think) is the `w64`. You shouldn't really even need that argument, but SYMPHONY 5.6 is using an old version of the build system that requires this workaround. 

To get 64-bit binaries, you just need to use the 64-bit version of gcc. Just make sure that the `msys64\mingw64` directory comes first in your path.
