### ISSUE TITLE
SYMPHONY does not compile with gcc 6

### ISSUE THREAD

**Issue by herbstk** [coin-or/SYMPHONY#2]
Trying to compile SYMPHONY with GCC version 6 (Debian Sid) aborts with the following error:
```
../include/sym_constants.h:358:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedanti ]
 }
 ^
Master/master_func.c:1793:52: note: in expansion of macro 'COMPARE_CAN_STR_ARRAY'
    str_int compare_can_str[COMPARE_CAN_STR_SIZE] = COMPARE_CAN_STR_ARRAY;
```

GCC 5 seems to work.

**Comment by tkralphs** [comment]
Can you try changing 
```
#ifdef _OPENMP
```
[here](https://github.com/coin-or/SYMPHONY/blob/master/SYMPHONY/include/sym_types.h#L288) to
```
#ifdef XXX
```
I don't recall why the OpenMP case was treated differently (this line of code goes back before I started using version control for development 14+ years ago), but it seems to work fine for me after the change and I guess it should fix the compiler error.

**Comment by herbstk** [comment]
This solved it for me, thank you very much.

**Comment by tkralphs** [comment]
Great! Fix now committed in trunk.
