### ISSUE TITLE
Issues finding `CglLandP.hpp` when compiling from source

### ISSUE THREAD

**Issue by pat-s** [coin-or/SYMPHONY#207]
Trying to compile on RHEL/Alma.

I've installed all dependencies from source (using the latest release tags as of today). When compiling SYMPHONY, I eventually run into this error:

```
#16 3.087 Making install in src
#16 3.097 make[1]: Entering directory '/SYMPHONY/src'
#16 3.099   CXX      Master/main.o
#16 3.146 In file included from ../include/sym_cg.h:22,
#16 3.146                  from ../include/sym_tm.h:24,
#16 3.146                  from ../include/sym_master.h:27,
#16 3.146                  from Master/main.cpp:55:
#16 3.146 ../include/sym_lp_solver.h:71:10: fatal error: CglLandP.hpp: No such file or directory
#16 3.146  #include "CglLandP.hpp"
```

AFAIU `CglLand` should be bundled within `Cgl` when compiling the latter from source.
Is there anything I am missing? Couldn't find any reference to this error, so I am opening this issue.

**Comment by pat-s** [comment]
Got it working by using `coinbrew`, yet the error is still strange to me.

**Comment by tkralphs** [comment]
Indeed, this is strange, but glad you got it working!
