### ISSUE TITLE
OpenMP support in Windows

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#56]
Issue created by migration from Trac.

Original creator: @tkralphs

Original creation time: 2006-11-21 00:43:19

Assignee: menal

Version: 5.1

Enable OpenMP support in MSVC++ 8

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2006-12-11 18:46:20

Changing assignee from menal to @tkralphs.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2006-12-11 18:46:20

Changing status from new to assigned.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2006-12-11 18:46:20

Version: Version changed from 5.1 to trunk (SVN)

**Comment by tkralphs** [comment]
This support is now working.
