### ISSUE TITLE
Symphony 5.1.4 with MS Visual Studio 2005 Professional

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#73]
Issue created by migration from Trac.

Original creator: jcheng

Original creation time: 2007-07-10 14:57:36

Assignee: @tkralphs

Version: 

The Win32\v8\symphony.vcproj does not include AdditionalDependencies

			<Tool
				Name="VCLinkerTool"
				OutputFile=".\Debug/symphony.exe"
				LinkIncremental="2"
				SuppressStartupBanner="true"
				IgnoreDefaultLibraryNames="odbc32.lib;odbccp32.lib"
				GenerateDebugInformation="true"
				ProgramDatabaseFile=".\Debug/symphony.pdb"
				SubSystem="1"
				TargetMachine="1"
			/>

After the AdditionalDependencies  was added after Name="VCLinkerTool"

				AdditionalDependencies=".\Debug\libsymphony.lib .\cgl\libcgl\debug\libcgl.lib .\clp\libclp\debug\libclp.lib .\Osi\libOsiclp\debug\libosiclp.lib .\osi\libosi\debug\libosi.lib .\clp\libclp\debug\libclp.lib .\coinutils\libcoinutils\debug\libcoinutils.lib"

The binary was generated with some warnings.  The generated binary was tested with pp08CUTS.mps of MIPLib2003.   The run produced cost solution of 7350.  The run took about 11 minutes on a Dell Pentium 4 2.8GHz under Windows XP.    

Similar AdditionalDependencies must be added for .\Release\Symphony.exe.

**Comment by tkralphs** [comment]
Closed because it refers to an old version.
