### ISSUE TITLE
Symphony 5.1.4, gesa2-o.mps of MIPLIB 2003, and  leMatrixRow.getElements()

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#75]
Issue created by migration from Trac.

Original creator: jcheng

Original creation time: 2007-07-18 17:46:10

Assignee: @tkralphs

Version: 

I tried to solve gesa2-o.mps of MIPLIB 2003 using Microsoft Visual Studio 2005 Professional generated executable.

In int CglKnapsackCover::deriveAKnapsack (CglKnapsackCover.cpp), it is noticed that leMatrixRow.getElements() is NULL.

Will you please tell me if NULL is correct.

If not correct, will you please tell me how to identify what caused the NULL. 

Thanks.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2007-07-22 21:08:15

Can you clarify your report a little? Are you saying that SYMPHONY 5.1.4 crashes when solving this instance? Can you describe exactly how to duplicate this behavior? What command-line arguments did you give it?

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2007-07-22 21:08:15

Changing status from new to assigned.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2007-07-22 21:10:13

Version: Version: 5.1.4

**Comment by tkralphs** [comment]
Closed because it refers to an old version.
